---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: atm-10-rcon-password
spec:
  length: 64
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atm-10-rcon-password
spec:
  refreshPolicy: CreatedOnce
  target:
    name: atm-10-rcon-password
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: atm-10-rcon-password
