---
# --- ServiceAccount that VSO will use to auth to Vault
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/secrets.hashicorp.com/vaultconnection_v1beta1.json
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
spec:
  address: http://vault-active.vault-system:8200
  skipTLSVerify: false
---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/secrets.hashicorp.com/vaultauth_v1beta1.json
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: minecraft-auth
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault
    audiences:
      - vault
    serviceAccount: vault
    tokenExpirationSeconds: 600
---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/secrets.hashicorp.com/vaultstaticsecret_v1beta1.json
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cf-api-key
  namespace: infra
spec:
  vaultAuthRef: minecraft-auth

  mount: kv
  type: kv-v2
  path: curseforge/api-key

  refreshAfter: 1h

  destination:
    create: true
    name: cf-api-key
