apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cf-api-key
  namespace: infra
spec:
  mount: kv
  type: kv-v2
  path: curseforge/api-key

  refreshAfter: 1h

  destination:
    create: true
    name: cf-api-key
