---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./postgres-creds.yaml
  - ./secret.yaml

  # TODO: enable these when the secrets are ready
  # - ./helmrelease.yaml
  # - ./middleware.yaml
