---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./postgres-creds.yaml
  - ./secret.yaml
  - ./helmrelease.yaml
  - ./middleware.yaml
