---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authentik-secretkey
spec:
  length: 64
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
spec:
  refreshPolicy: CreatedOnce
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        SECRET_KEY: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: authentik-secretkey
