---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: decluttarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      decluttarr:
        containers:
          app:
            image:
              repository: ghcr.io/bsfishy/decluttarr
              tag: yaml_env@sha256:c7667c3f170cdbd7973e46e2cfc3ca0f413f78304653d9e350e7a7d71fb64dc5

            env:
              - name: TZ
                value: America/Chicago
              - name: RADARR_API_KEY
                secretKeyRef:
                  name: "radarr-secret"
                  key: "RADARR__AUTH__APIKEY"
              - name: SONARR_API_KEY
                secretKeyRef:
                  name: "sonarr-secret"
                  key: "SONARR__AUTH__APIKEY"

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                cpu: 100m
              limits:
                memory: 4Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      media:
        existingClaim: media
        globalMounts:
          - path: /media

      config-file:
        type: configMap
        name: "decluttarr-config"
        globalMounts:
          - path: /app/config/config.yaml
            subPath: config.yaml

      tmpfs:
        type: emptyDir
        advancedMounts:
          decluttarr:
            app:
              - path: /app/logs
                subPath: logs
