---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
spec:
  chartRef:
    kind: OCIRepository
    name: coredns
  interval: 30m
  values:
    serviceType: LoadBalancer

    prometheus:
      service:
        enabled: true
      monitor:
        enabled: true

    service:
      # TODO: add ipv6 ip
      loadBalancerIP: 10.1.3.4

    # dont try to replace the cluster coredns
    isClusterService: false

    servers:
      # TODO: support DoH and DoT with tls plugin
      - zones:
          - zone: .
            use_tcp: true
        port: 53
        plugins:
          - name: debug
          - name: errors
          - name: health
            configBlock: |-
              lameduck 10s
          - name: ready
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: home.mattprovost.dev 10.1.3.5
          - name: forward
            parameters: k8s.mattprovost.dev 10.1.3.5
          - name: forward
            parameters: . tls://1.1.1.1 tls://1.0.0.1
            configBlock: |-
              tls_servername cloudflare-dns.com
              health_check 5s
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
