---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pajikos
spec:
  interval: 30m
  url: https://pajikos.github.io/home-assistant-helm-chart/
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: home-assistant
      version: 0.3.17
      sourceRef:
        kind: HelmRepository
        name: pajikos
  values:
    podAnnotations:
      "k8s.v1.cni.cncf.io/networks": home-assistant

    service:
      type: ClusterIP

    livenessProbe:
      timeoutSeconds: 5
    readinessProbe:
      timeoutSeconds: 5

    ingress:
      enabled: true
      hosts:
        - host: ha.home.mattprovost.dev
          paths:
            - path: /
              pathType: Prefix

    configuration:
      enabled: true
      forceInit: true
      trusted_proxies:
        - 10.244.0.0/16

    persistence:
      enabled: true
      storageClass: ceph-regular

    deploymentStrategy: Recreate
