---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      home-assistant:
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: home-assistant
          securityContext:
            runAsUser: 65534
            runAsGroup: 65533
            fsGroup: 65533
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.8.3
            env:
              VENV_FOLDER: /venv
            resources:
              requests:
                cpu: 47m
                memory: 2Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        primary: true
        type: LoadBalancer
        sessionAffinity: ClientIP
        ports:
          http:
            port: 8123

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        storageClass: longhorn
        advancedMounts:
          home-assistant:
            app:
              - path: /config
      hass-cache:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 8Gi
        storageClass: low-priority
        advancedMounts:
          home-assistant:
            app:
              - path: /venv
                subPath: hass-venv
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /tmp
                subPath: hass-tmp

    route:
      app:
        hostnames:
          - ha.home.mattprovost.dev
        parentRefs:
          - name: traefik-gateway
            namespace: infra
            sectionName: websecure
        rules:
          - backendRefs:
              - identifier: app
                port: 8123
