---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: home-assistant
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "br0",
    "mode": "bridge",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "10.1.3.6/16",
          "gateway": "10.1.0.1"
        }
      ]
    }
  }'
