---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-ca-issuer
spec:
  ca:
    secretName: tls-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ca
spec:
  isCA: true
  commonName: Vault Local CA
  secretName: tls-ca
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server
spec:
  secretName: tls-server
  dnsNames:
    - vault-0.vault-internal
    - vault-1.vault-internal
    - vault-2.vault-internal
  issuerRef:
    name: vault-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ingress
spec:
  secretName: tls-ingress
  commonName: "vault.home.mattprovost.dev"
  dnsNames:
    - "vault.home.mattprovost.dev"
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: internal-tls
spec:
  rootCAsSecrets:
    - tls-ca
