apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: vault
  namespace: vault-system
spec:
  parentRefs:
    - name: edge
      namespace: infra
      sectionName: tls-passthrough
  hostnames: ["vault.home.mattprovost.dev"]
  rules:
    - backendRefs:
        - name: vault-active
          port: 8200
