apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
spec:
  secretName: wildcard-tls
  commonName: "home.mattprovost.dev"
  dnsNames:
    - "home.mattprovost.dev"
    - "*.home.mattprovost.dev"
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
