apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
spec:
  gatewayClassName: traefik
  listeners:
    # Exact host, raw TLS passthrough to Ceph
    - name: tls-passthrough
      # hostname: ceph.home.mattprovost.dev
      port: 8443
      protocol: TLS
      tls:
        mode: Passthrough
      allowedRoutes:
        kinds:
          - kind: TLSRoute
        namespaces:
          from: All

    # Everything else terminated at Traefik with your wildcard cert
    - name: websecure
      # hostname: "*.home.mattprovost.dev"
      port: 8443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: wildcard-tls
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
