---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: infra
spec:
  entryPoints:
    - websecure
    - traefik
  routes:
    - kind: Rule
      match: Host(`traefik.home.mattprovost.dev`)
      # middlewares:
      #   - name: authentik-authentik@kubernetescrd
      services:
        - kind: TraefikService
          name: api@internal
