---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-regular
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-metadata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-regular
