---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/home-operations/charts-mirror/cilium
  ref:
    tag: 1.18.1
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  chartRef:
    kind: OCIRepository
    name: cilium
  interval: 30m
  values:
    autoDirectNodeRoutes: true
    bandwidthManager:
      bbr: true
      enabled: true
    bgpControlPlane:
      enabled: true
    bpf:
      datapathMode: netkit
      masquerade: true
      preallocateMaps: true
    bpfClockProbe: true
    cgroup:
      automount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    cluster:
      id: 1
      name: main
    cni:
      exclusive: false
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium
    devices: br+
    endpointRoutes:
      enabled: true
    envoy:
      rollOutPods: true
      prometheus:
        serviceMonitor:
          enabled: true
    gatewayAPI:
      enabled: true
      enableAlpn: true
      xffNumTrustedHops: 1
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: infra-authentik@kubernetescrd
          hosts:
            - hubble.home.mattprovost.dev
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: 10.244.0.0/16
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 7445
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    l2announcements:
      enabled: false
    loadBalancer:
      algorithm: maglev
      mode: dsr
    localRedirectPolicy: true
    operator:
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Cilium
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      replicas: 2
      rollOutPods: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    rollOutCiliumPods: true
    routingMode: native
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - PERFMON
          - BPF
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    ipv6:
      enabled: true
    enableIPv6Masquerade: true
