---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: qbittorrent
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "qbittorrent",
      "plugins": [
        {
          "type": "macvlan",
          "master": "br0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "addresses": [{
              "address": "10.1.3.9/16",
              "gateway": "10.1.0.1"
            }]
          }
        },
        { "type": "sbr" }
      ]
    }
