---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.2.1
  url: oci://ghcr.io/home-operations/charts-mirror/alloy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: alloy
  values:
    fullnameOverride: alloy
    alloy:
      configMap:
        create: false
        name: alloy-configmap
        key: config.alloy
    serviceMonitor:
      enabled: true
