---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crunchy-userinit
spec:
  interval: 30m
  url: https://drummyfloyd.github.io/crunchy-userinit-controller
  timeout: 3m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: userinit-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: crunchy-userinit-controller
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: crunchy-userinit
