---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # vendored to make talos changes (https://www.talos.dev/v1.10/kubernetes-guides/network/multus/)
  - ./multus-daemonset-thick.yaml
