---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.39.0
  url: oci://ghcr.io/grafana/helm-charts/loki
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: loki
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  valuesFrom:
    - targetPath: loki.storage.s3.accessKeyId
      kind: Secret
      name: &s3Secret loki-s3
      valuesKey: key_id
    - targetPath: loki.storage.s3.secretAccessKey
      kind: Secret
      name: *s3Secret
      valuesKey: secret_key
  values:
    deploymentMode: SimpleScalable

    loki:
      analytics:
        reporting_enabled: false
      auth_enabled: false
      commonConfig:
        replication_factor: 2
      ingester:
        chunk_encoding: snappy

      extraMemberlistConfig:
        randomize_node_name: false
        advertise_addr: ${POD_IP}

      compactor:
        working_directory: /var/loki/compactor/retention
        delete_request_store: s3
        retention_enabled: true

      limits_config:
        retention_period: 14d

      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

      server:
        log_level: info

      storage:
        type: s3
        s3:
          endpoint: s3.home.mattprovost.dev:9000
          region: us-east-1
          s3ForcePathStyle: true
          insecure: true

        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin

    backend: &service
      replicas: 2
      extraArgs:
        - -config.expand-env=true
      extraEnv:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
    read: *service
    write: *service
    gateway:
      replicas: 2

    chunksCache:
      enabled: true
    resultsCache:
      enabled: true

    sidecar:
      image:
        repository: ghcr.io/home-operations/k8s-sidecar
        tag: 1.30.10@sha256:dd3b1f0c4e6b4512b2deb50c58acf65fd0f0927120a59a95eec854d32a6c9ce3
      enableUniqueFilenames: true
      rules:
        searchNamespace: ALL
        folder: /rules/fake

    lokiCanary:
      enabled: false
    test:
      enabled: false
