---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.39.0
  url: oci://ghcr.io/grafana/helm-charts/loki
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: loki
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    deploymentMode: SimpleScalable

    loki:
      analytics:
        reporting_enabled: false
      auth_enabled: false
      commonConfig:
        replication_factor: 2

      compactor:
        working_directory: /var/loki/compactor/retention
        delete_request_store: s3
        retention_enabled: true

      limits_config:
        retention_period: 14d

      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

      server:
        log_level: info

      storage:
        type: s3
        s3:
          endpoint: minio.database.svc.cluster.local
          region: us-east-1
          s3ForcePathStyle: true
          insecure: true

          # pull from env (set below)
          accessKeyId: ${S3_ACCESS_KEY_ID}
          secretAccessKey: ${S3_SECRET_ACCESS_KEY}

          bucketNames:
            chunks: loki-chunks
            ruler: loki-ruler
            admin: loki-admin

    backend:
      replicas: 2
      extraArgs:
        - -config.expand-env=true
      extraEnv:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: loki-s3
              key: key_id
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: loki-s3
              key: secret_key
    read:
      replicas: 2
      extraArgs:
        - -config.expand-env=true
      extraEnv:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: loki-s3
              key: key_id
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: loki-s3
              key: secret_key
    write:
      replicas: 2
      extraArgs:
        - -config.expand-env=true
      extraEnv:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: loki-s3
              key: key_id
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: loki-s3
              key: secret_key
    gateway:
      replicas: 2
    singleBinary:
      replicas: 0

    chunksCache:
      enabled: true
    resultsCache:
      enabled: true

    sidecar:
      image:
        repository: ghcr.io/home-operations/k8s-sidecar
        tag: 1.30.10@sha256:dd3b1f0c4e6b4512b2deb50c58acf65fd0f0927120a59a95eec854d32a6c9ce3
      enableUniqueFilenames: true
      rules:
        searchNamespace: ALL
        folder: /rules/fake

    lokiCanary:
      enabled: false
    test:
      enabled: false
