---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./traefik/ks.yaml
  - ./k8s_gateway/ks.yaml
  - ./coredns/ks.yaml
