---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  interval: 30m
  values:
    domain: mattprovost.dev

    # since this is split horizon, the ttls should be very short so roaming is quick
    ttl: 5

    service:
      type: LoadBalancer
      loadBalancerIP: 10.1.3.5

    debug:
      enabled: true
