apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: label-pvc-by-storageclass
spec:
  background: true
  rules:
    - name: label-pvc-storage-tier
      match:
        any:
          - resources:
              kinds: ["PersistentVolumeClaim"]
      preconditions:
        all:
          - key: "{{ (target.spec.storageClassName || request.object.spec.storageClassName || '') }}"
            operator: NotEquals
            value: ""
      mutate:
        mutateExistingOnPolicyUpdate: true
        targets:
          - apiVersion: v1
            kind: PersistentVolumeClaim
        patchStrategicMerge:
          metadata:
            labels:
              storage-tier: >-
                {{ replace_all(
                     (target.spec.storageClassName || request.object.spec.storageClassName),
                     'ceph-',
                     ''
                   ) }}
