---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: forgejo
spec:
  type: oci
  interval: 5m
  url: oci://code.forgejo.org/forgejo-helm
---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  interval: 2h
  chart:
    spec:
      chart: forgejo
      version: 14.0.3
      sourceRef:
        kind: HelmRepository
        name: forgejo
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    strategy:
      type: Recreate
    service:
      ssh:
        type: LoadBalancer
        port: 22
        annotations:
          external-dns.alpha.kubernetes.io/hostname: git-ssh.home.mattprovost.dev
    persistence:
      enabled: true
      create: false
      claimName: forgejo
    valkey-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
    postgresql:
      enabled: false

    gitea:
      # See https://forgejo.org/docs/latest/admin/config-cheat-sheet/
      config:
        actions:
          ENABLED: false
        cache:
          ADAPTER: redis
          HOST: redis://redis-master.database.svc.cluster.local:6379/3?pool_size=100&idle_timeout=180s
        database:
          DB_TYPE: postgres
          SSL_MODE: require
          HOST: postgres-primary.database.svc.cluster.local
          name: forgejo
        mailer:
          ENABLED: false
        migrations:
          ALLOWED_DOMAINS: "github.com,*.github.com,gitlab.com,*.gitlab.com,*.mattprovost.dev"
        oauth2:
          ACCOUNT_LINKING: auto
          ENABLE_AUTO_REGISTRATION: true
          OPENID_CONNECT_SCOPES: "openid email groups"
          UPDATE_AVATAR: true
          USERNAME: nickname
        openid:
          ENABLE_OPENID_SIGNIN: false
          ENABLE_OPENID_SIGNUP: false
          WHITELISTED_URIS: auth.home.mattprovost.dev
        queue:
          CONN_STR: redis://redis-master.database.svc.cluster.local:6379/3?pool_size=100&idle_timeout=180s
          TYPE: redis
        repository:
          DEFAULT_PRIVATE: private
        security:
          PASSWORD_COMPLEXITY: spec
        server:
          ROOT_URL: https://git.home.mattprovost.dev
          SSH_DOMAIN: git-ssh.home.mattprovost.dev
          SSH_LISTEN_PORT: 2222
          SSH_PORT: 22
        service:
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
          DISABLE_REGISTRATION: false
          ENABLE_NOTIFY_MAIL: true
          REQUIRE_SIGNIN_VIEW: true
          SHOW_REGISTRATION_BUTTON: false
        session:
          PROVIDER: redis
          PROVIDER_CONFIG: redis://redis-master.database.svc.cluster.local:6379/3?pool_size=100&idle_timeout=180s
        storage:
          STORAGE_TYPE: minio
          MINIO_ENDPOINT: s3.home.mattprovost.dev
          MINIO_BUCKET: forgejo
          MINIO_USE_SSL: true
        webhook:
          ALLOWED_HOST_LIST: private
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      oauth:
        - adminGroup: admins
          autoDiscoverUrl: https://auth.home.mattprovost.dev/application/o/forgejo/.well-known/openid-configuration
          existingSecret: forgejo-oauth-secret
          groupClaimName: groups
          iconUrl: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/png/authentik.png
          name: Authentik
          provider: openidConnect
          scopes: openid profile email

  valuesFrom:
    - kind: Secret
      name: &s3Secret forgejo-s3
      valuesKey: key_id
      targetPath: gitea.config.storage.MINIO_ACCESS_KEY_ID
    - kind: Secret
      name: *s3Secret
      valuesKey: secret_key
      targetPath: gitea.config.storage.MINIO_SECRET_ACCESS_KEY
    - kind: Secret
      name: forgejo-secret
      valuesKey: secret
      targetPath: gitea.config.security.SECRET_KEY
    - kind: Secret
      name: &dbSecret forgejo-postgres-creds
      valuesKey: username
      targetPath: gitea.config.database.USER
    - kind: Secret
      name: *dbSecret
      valuesKey: password
      targetPath: gitea.config.database.PASSWD
