---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snap-hourly
  namespace: longhorn-system
spec:
  cron: "0 * * * *" # top of every hour
  task: snapshot
  groups: ["default", "critical"] # attach this to most volumes
  retain: 24 # 24 hours of hourly snaps
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-nightly
  namespace: longhorn-system
spec:
  cron: "0 3 * * *" # 03:00 nightly
  task: backup
  groups: ["critical"] # only volumes you mark "critical"
  retain: 14 # 14 days of backups
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  cron: "0 4 * * 0" # Sundays 04:00
  task: backup
  groups: ["default"] # lower-priority stuff
  retain: 5 # ~5 weeks
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snap-media
  namespace: longhorn-system
spec:
  cron: "0 3 * * *" # 04:00 nightly
  task: snapshot
  groups: ["media"] # attach this to most volumes
  retain: 14 # 14 days of backups
  concurrency: 2
