---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-secrets-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: vault-secrets-operator
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  values:
    defaultVaultConnection:
      enabled: true
      address: "http://vault-active.vault-system:8200"
      skipTLSVerify: false
