apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: set-forwarded-proto
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ceph-dashboard
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: rook-ceph-set-forwarded-proto@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: ceph.home.mattprovost.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rook-ceph-mgr-dashboard
                port:
                  number: 7000
