---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mc-router
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.4.0
  url: oci://ghcr.io/itzg/minecraft-server-charts/mc-router
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: router
spec:
  chartRef:
    kind: OCIRepository
    name: mc-router
  interval: 30m
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Service
              name: router-mc-router
              namespace: minecraft
            patch: |
              - op: add
                path: /metadata/labels/well-known
                value: "true"
  values:
    services:
      minecraft:
        type: LoadBalancer
        annotations:
          "lbipam.cilium.io/ips": "10.1.3.6,2603:8080:1e00:1b02:2000::3"
          "coredns.io/hostname": "mc.mattprovost.dev"

      extraServiceSpec:
        ipFamilyPolicy: PreferDualStack
        externalTrafficPolicy: Local

    minecraftRouter:
      defaultServer:
        host: atm-10-minecraft.minecraft.svc.cluster.local
        port: 25565

      mappings:
        - externalHostname: atm10.mc.mattprovost.dev
          host: atm-10-minecraft.minecraft.svc.cluster.local
          port: 25565
