---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atm-10-rcon-admin
spec:
  interval: 5m
  chart:
    spec:
      chart: rcon-web-admin
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      host: atm-10.home.mattprovost.dev
      pathType: Prefix
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: infra-authentik@kubernetescrd

    rconWeb:
      isAdmin: true
      serverName: atm-10
      rconHost: atm-10-minecraft-rcon.svc.cluster.local
      rconPasswordExistingSecret: atm-10-rcon-password
      rconPasswordKey: password
