---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: itzg
spec:
  interval: 30m
  provider: generic
  timeout: 3m
  url: https://itzg.github.io/minecraft-server-charts/
